#!/bin/sh
# This script is used for testing the build, primarily for use
# with travis, but may be used by hand as well.

set -e

# Clean up
clean()
{
    mvn clean
}

# Test maven build
maven()
{
    mvn
    clean
}

for arg in "$@"
do
    case $arg in
        clean)
            clean ;;
        maven)
            maven ;;
        all)
            clean && maven ;;
        *)
            echo "Invalid argument: \"$arg\"" >&2
            exit 1
            ;;
    esac
done

exit 0